workflows:
  build-ios:
    name: Build iOS from monorepo
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: |
          cd apps/cashapp_flutter
          flutter pub get
      - name: Build iOS
        script: |
          cd apps/cashapp_flutter
          flutter build ios --release --no-codesign
    artifacts:
      - apps/cashapp_flutter/build/ios/ipa/*.ipa
      - apps/cashapp_flutter/build/ios/ipa/*.app
    publishing:
      email:
        recipients:
          - screamott1@email.com
